---

# The configuration allows for you to turn of aspects of the build if you want to use your own setup.  Just set docker_instance to false and configure with the details of the component in your environment.
# If the docker_instance is set to false, it will use the credentials to check for connectivity, on the manually configured hosts
#
# Ldap type is either 'Open' for OpenLDAP or 'AD' for Active Directory.  If using Active Directory, the docker_instance variable  has to be false
#

# Path where the GIT repo is located
repo_path: /root/bastion-proxy/

# Vault Config
vault:  { 
  docker_instance: true,
  version: 0.9.6,
  host: vault,
  vault_port: 9100,
  token: ''
}

# OpenLDAP or AD LDAP Config.
ldap: {  
  docker_instance: true,
  ldap_type: Open,
  host: ldap,
  ldap_port: 385
}

# ProxySQL Config
proxysql: {
  docker_instance: true,
  host: proxysql,
  proxysql_port: 3306,
  admin_user: admin,
  admin_pass: <adminpass>,
  remote_admin_user: radmin,
  remote_admin_pass: <radminpass>
}

# MySQL Inventory Config
mysql_inventory: {
  docker_instance: true,
  host: localhost,
  mysql_port: 3306,
  user: root,
  pass: mysql_inventory_password,
  mysql_remote_user: remote_user,
  mysql_remote_pass: <pass>
}
